# Generated by Django 4.1.7 on 2023-03-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
