# Generated by Django 4.1.7 on 2023-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='pddikti',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='university',
            field=models.CharField(max_length=50),
        ),
    ]
