# Generated by Django 4.1.7 on 2023-03-16 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor_register', '0002_alter_tutor_pddikti_alter_tutor_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
