# Generated by Django 4.1.7 on 2023-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0003_alter_tutor_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='ktm_person',
            field=models.ImageField(null=True, upload_to='ktm_person'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ktp',
            field=models.FileField(upload_to='ktm'),
        ),
         migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(max_length=25),
        ),
    ]
