# Generated by Django 4.1.7 on 2023-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0004_tutor_ktm_person_alter_tutor_ktp_alter_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='ktm_person',
            field=models.ImageField(upload_to='ktm_person'),
        ),
    ]
