# Generated by Django 4.1.7 on 2023-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0005_alter_tutor_ktm_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(max_length=25),
        ),
    ]
