# Generated by Django 4.1.7 on 2023-03-18 17:25

from django.db import migrations, models
import tutor_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0006_alter_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='ktm_person',
            field=models.ImageField(upload_to=tutor_register.models.upload_ktm_person),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ktp',
            field=models.FileField(upload_to=tutor_register.models.upload_ktm),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='transkrip',
            field=models.FileField(upload_to=tutor_register.models.upload_transkrip),
        ),
    ]
