# Generated by Django 4.1.7 on 2023-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_register', '0009_tutor_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='price',
        ),
        migrations.AddField(
            model_name='tutor',
            name='price_per_hour',
            field=models.FloatField(default=35000),
        ),
    ]
