# Generated by Django 4.1.7 on 2023-05-05 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_register", "0010_remove_tutor_price_tutor_price_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="review_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
