# Generated by Django 4.1.7 on 2023-05-04 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor_register', '0010_remove_tutor_price_tutor_price_per_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_alter_schedule_tutor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('snap_token', models.CharField(max_length=100, null=True)),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_register.tutor')),
            ],
        ),
    ]
