# Generated by Django 4.1.7 on 2023-05-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='schedule_id',
            new_name='schedule',
        ),
    ]
