# Generated by Django 4.1.7 on 2023-04-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_register", "0007_alter_tutor_ktm_person_alter_tutor_ktp_and_more"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="tutor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tutor_register.tutor",
            ),
        ),
    ]
